export const data = {
  name: 'Yustin Eduardo Pérez Castro',
  title: 'Data Analyst & Data Engineer in Training',
  subtitle: 'Building end-to-end data solutions · Python · SQL · Power BI · dbt · Kafka',
  // Rotating phrases for the hero typewriter effect
  heroRoles: [
    'GBS Web Scraping & Data Engineering Intern @ Equifax',
    'ETL · dbt · Kafka · Airflow',
    '100k+ Records Per Dataset',
  ],
  // Real snippet rendered in the hero terminal card.
  // Each line is an array of tokens {c: cssClass, t: text} for CSS-only highlighting.
  heroSnippet: {
    file: 'etl_crypto_dag.py',
    repo: 'github.com/yustin-prz/etl-crypto-airflow',
    lines: [
      [{ c: 'kw', t: 'from' }, { c: '', t: ' airflow ' }, { c: 'kw', t: 'import' }, { c: 'cls', t: ' DAG' }],
      [{ c: 'kw', t: 'from' }, { c: '', t: ' airflow.operators.python ' }, { c: 'kw', t: 'import' }, { c: 'cls', t: ' PythonOperator' }],
      [{ c: 'kw', t: 'from' }, { c: '', t: ' datetime ' }, { c: 'kw', t: 'import' }, { c: 'cls', t: ' datetime' }],
      [],
      [{ c: 'com', t: '# Daily ETL — extract ▸ transform ▸ load ▸ validate' }],
      [{ c: 'kw', t: 'with' }, { c: 'cls', t: ' DAG' }, { c: 'op', t: '(' }],
      [{ c: '', t: '    ' }, { c: 'str', t: '"crypto_etl"' }, { c: 'op', t: ',' }],
      [{ c: '', t: '    ' }, { c: 'param', t: 'schedule' }, { c: 'op', t: '=' }, { c: 'str', t: '"@daily"' }, { c: 'op', t: ',' }],
      [{ c: '', t: '    ' }, { c: 'param', t: 'start_date' }, { c: 'op', t: '=' }, { c: 'cls', t: 'datetime' }, { c: 'op', t: '(' }, { c: 'num', t: '2025' }, { c: 'op', t: ', ' }, { c: 'num', t: '1' }, { c: 'op', t: ', ' }, { c: 'num', t: '1' }, { c: 'op', t: '),' }],
      [{ c: '', t: '    ' }, { c: 'param', t: 'catchup' }, { c: 'op', t: '=' }, { c: 'kw', t: 'False' }, { c: 'op', t: ',' }],
      [{ c: 'op', t: ') ' }, { c: 'kw', t: 'as' }, { c: '', t: ' dag' }, { c: 'op', t: ':' }],
      [],
      [{ c: '', t: '    extract ' }, { c: 'op', t: '>>' }, { c: '', t: ' transform ' }, { c: 'op', t: '>>' }, { c: '', t: ' load' }],
      [{ c: '', t: '             ' }, { c: 'op', t: '>>' }, { c: '', t: ' validate' }],
    ],
  },
  bio: 'Software Engineering student who turns raw data into production pipelines and decisions. Currently a Web Scraping & Data Engineering Intern at Equifax\'s Global Business Services (GBS). Previously built data solutions over datasets of 100,000+ records for DHL\'s Accounts Receivable team, where I re-engineered a critical pipeline and cut its execution time by 75% — a solution now scaling across 8 South American countries. I ship end-to-end data systems — orchestrated with Airflow, streamed with Kafka, modeled with dbt — backed by 10 open-source projects.',
  email: 'perezcastroyus23@gmail.com',
  linkedin: 'https://linkedin.com/in/yustin-prz',
  github: 'https://github.com/yustin-prz',
  // Downloadable CV/resume (PDF in /public). ATS-optimized, phone removed for privacy.
  resumeUrl: '/Yustin_Perez_CV.pdf',
  location: 'Alajuela, Costa Rica',
  // About cards (kept here so no content is hardcoded in components)
  about: [
    { icon: '🏢', title: 'Current role', text: 'Web Scraping & Data Engineering Intern at Equifax Global Business Services (GBS). Previously Data Engineering Intern on the RPA & Innovation team at DHL Shared Service Center Americas, Heredia.' },
    { icon: '🎓', title: 'Education', text: "Bachelor's Degree in Software Engineering at Universidad Técnica Nacional (2025 – Present). Associate's Degree in Information Technologies, 2025." },
    { icon: '📍', title: 'Location', text: 'Alajuela, Costa Rica. Open to remote roles worldwide and hybrid positions in the Greater Metropolitan Area.' },
    { icon: '🗣️', title: 'Languages', text: 'Spanish (native) · English C1 Advanced (EF SET Certified). All documentation and portfolio content in English.' },
  ],
  // value/suffix split so the hero stats can animate with a count-up effect
  stats: [
    { value: 10, suffix: '', label: 'Projects published' },
    { value: 100, suffix: 'k+', label: 'Records per dataset' },
    { value: 7, suffix: '', label: 'Certifications' },
  ],
  // Impact section — animated metric cards (between About and Experience)
  impact: [
    {
      icon: '⚡',
      prefix: '-',
      value: 75,
      suffix: '%',
      label: 'Pipeline execution time',
      sub: 'Re-engineered the AR pipeline at DHL',
    },
    {
      icon: '🌎',
      value: 8,
      suffix: '',
      label: 'Countries scaling',
      sub: 'AR pipeline rolling out across South America',
    },
    {
      icon: '🗄️',
      value: 100,
      suffix: 'k+',
      label: 'Records per dataset',
      sub: 'For the Accounts Receivable team',
    },
    {
      icon: '✅',
      value: 11,
      suffix: '/11',
      label: 'Data quality tests passing',
      sub: 'dbt warehouse — all green',
    },
  ],
  experience: [
    {
      company: 'Equifax Costa Rica',
      role: 'Web Scraping & Data Engineering Intern',
      location: 'San José, Costa Rica',
      date: 'Jul 2026 – Present',
      active: true,
      tech: ['Python', 'Docker', 'Kubernetes', 'AWS', 'Jenkins', 'Playwright', 'CI/CD'],
      bullets: [
        'Run CI/CD pipelines (Jenkins, GitHub) across a Docker/Kubernetes/AWS stack that keep Equifax\'s Web Scraping data-collection services deploying reliably to production.',
        'Keep mission-critical data-extraction pipelines resilient against constantly shifting external sources — resolving site-structure changes, credential rotations and dependency drift before they break downstream reporting.',
        'Raised code-repository standards for the Web Scraping team, tightening version control practices and speeding up knowledge transfer across the team.',
        'Protect the integrity of data feeding Equifax\'s global credit-information products — trusted by financial institutions worldwide — through systematic cleaning, normalization and validation.',
      ],
    },
    {
      company: 'DHL Express',
      role: 'SSC Data Engineering Intern · RPA & Innovation Team',
      location: 'Belén, Heredia, Costa Rica',
      date: 'Oct 2025 – Jul 2026',
      active: false,
      tech: ['Python', 'SQL', 'Power Query', 'Power BI', 'Selenium', 'Power Apps', 'Excel VBA'],
      bullets: [
        'Developed analytical solutions for the Accounts Receivable team over datasets of 100,000+ records, automating reconciliation, collections tracking and financial reporting workflows.',
        'Re-engineered a critical data pipeline handling 100,000+ records, reducing execution time by 75% through automation and improved transformation logic.',
        'Scaled the solution — originally built for Central America and the Caribbean — across 8 South American countries: Argentina, Chile, Colombia, Peru, Brazil, Bolivia, Uruguay and Paraguay.',
        'Built interactive Power BI dashboards tracking operational and financial KPIs in real time, enabling faster data-driven decisions.',
        'Built data-transformation solutions in Power Query (M) and Python (Pandas) to extract, clean and validate structured data, ensuring data integrity across reporting outputs.',
        'Automated recurring reports with Excel VBA and Power Apps, and expanded data extraction using Selenium with Python and SQL.',
      ],
    },
    {
      company: 'Freelance',
      role: 'Web Developer',
      location: 'Costa Rica · Remote',
      date: 'May 2023 – Apr 2024',
      active: false,
      tech: ['Angular', 'JavaScript', 'SQL Server', 'HTML/CSS'],
      bullets: [
        'Designed relational SQL Server databases and built data visualization components, enabling clients to track business performance through custom analytical dashboards.',
        'Built REST APIs to automate data exchange between external services and internal systems across multiple formats.',
        'Translated client requirements into end-to-end solutions, managing the full project lifecycle from requirements gathering through delivery and documentation.',
      ],
    },
  ],
  // category drives the Projects filters; type stays as the display label.
  // highlight = key measurable outcome shown prominently (recruiters scan for metrics).
  projects: [
    {
      emoji: '🍽️',
      type: 'Full Stack',
      category: 'Backend',
      name: 'SnackFlow',
      highlight: 'Dockerized 3-tier app',
      desc: 'Full stack food ordering application. Frontend, backend and database layers with Docker containerization.',
      tech: ['JavaScript', 'Node.js', 'Docker', 'PostgreSQL'],
      url: 'https://github.com/yustin-prz/snackflow',
    },
    {
      emoji: '🤖',
      type: 'ML · Web App',
      category: 'ML',
      name: 'CryptoEdu Platform',
      highlight: '10 engineered features · 4-page app',
      desc: 'Educational ML platform with Prophet + XGBoost, interactive lessons, backtesting simulator and 10-question quiz. 4-page Streamlit web app with real-time data.',
      tech: ['Python', 'XGBoost', 'Prophet', 'Streamlit', 'PostgreSQL'],
      url: 'https://github.com/yustin-prz/crypto-ml-dashboard',
      demoUrl: 'https://crypto-ml-dashboard-hgkewdmkqni8dyuidsahmk.streamlit.app/',
      caseStudy: {
        problem: 'Most educational crypto tools either dump raw price charts on users or make bold price predictions without explaining the reasoning behind them — neither approach actually teaches how professional technical indicators work.',
        approach: 'Built an end-to-end pipeline: CoinGecko API → PostgreSQL (via SQLAlchemy) → engineered features (RSI, MACD, Bollinger Bands, moving averages, volume ratios) → a 4-page Streamlit app covering live market data, interactive indicator lessons, a strategy backtester and a quiz. Refactored the DB connection to read from environment variables / Streamlit secrets instead of a hardcoded local connection, so the same codebase runs identically in dev and production, then deployed it against a managed Postgres instance (Neon).',
        results: 'Live production app serving 4 coins with real-time data, 3 backtested trading strategies benchmarked against a HODL baseline, and a fully reproducible deploy path (populate DB → set secrets → deploy) that anyone can fork and stand up themselves.',
      },
    },
    {
      emoji: '⚡',
      type: 'Real-Time Streaming',
      category: 'Data Engineering',
      name: 'Kafka Crypto Streaming',
      highlight: '8 streams/sec · 650+ events/session',
      desc: 'Producer/consumer pipeline processing 8 concurrent crypto price streams per second. 650+ events per session persisted to PostgreSQL with Kafka UI monitoring.',
      tech: ['Apache Kafka', 'Docker', 'PostgreSQL', 'Python'],
      url: 'https://github.com/yustin-prz/kafka-crypto-streaming',
      caseStudy: {
        problem: 'Needed to prove out a real-time streaming architecture — continuously ingesting price events and persisting them reliably — without depending on a paid real-time market-data feed for a portfolio project.',
        approach: 'Built a producer/consumer pipeline around Apache Kafka. The producer simulates realistic price ticks for 8 coins using Gaussian random walks with per-coin volatility parameters (not naive random noise), publishing one event per coin per second to a crypto-prices topic. A consumer subscribes and persists every event to PostgreSQL in real time, logging throughput stats every 50 messages. Kafka UI runs alongside for live monitoring of topic and partition health, and the whole stack (Kafka, Zookeeper, Postgres) is containerized with Docker.',
        results: 'Sustained 8 events/sec throughput and 650+ events persisted per session. The bullish/bearish split converges to ~54% over time — consistent with the no-drift random-walk model used, which is the correct, expected outcome for a simulated feed with no directional bias (a real check on whether the simulation is behaving as designed).',
      },
    },
    {
      emoji: '🏗️',
      type: 'Data Warehouse',
      category: 'Data Engineering',
      name: 'dbt + DuckDB Warehouse',
      highlight: '11/11 data-quality tests · 38,865 rows',
      desc: 'Staging + marts architecture across 23 source tables (38,865 rows). 4 transformation models, 11 automated data quality tests (all passing). Full lineage documentation.',
      tech: ['dbt', 'DuckDB', 'SQL', 'Python'],
      url: 'https://github.com/yustin-prz/dbt-crypto-warehouse',
      demoUrl: 'https://yustin-prz.github.io/dbt-crypto-warehouse/',
      caseStudy: {
        problem: 'Raw historical price data for 23 cryptocurrencies existed only as 23 separate flat-file exports (2013–2021, ~38,865 rows combined) with no unified schema and no data-quality guarantees — the kind of fragmented-source problem real data teams hit when ingesting from multiple vendor exports.',
        approach: 'Built a staging + marts architecture in dbt on top of DuckDB (embedded, no server to manage). A single stg_coins model unifies all 23 source files via UNION ALL and standardizes column names and types. Three mart models layer on top: daily prices enriched with return metrics and sentiment, a historical performance summary per coin, and market-cap dominance by year. 11 automated data-quality tests (not-null, uniqueness) run on every build via dbt test, and the entire pipeline — seed, run, test, docs generate — executes in CI on every push, publishing live documentation automatically.',
        results: '11/11 tests passing on every CI run, 38,865 rows modeled across 4 tables, and full column-level lineage documentation published with zero manual steps to rebuild or redeploy the warehouse.',
      },
    },
    {
      emoji: '🔄',
      type: 'ETL Orchestration',
      category: 'Data Engineering',
      name: 'Airflow ETL Pipeline',
      highlight: 'Daily DAG · retry + validation',
      desc: 'Daily DAG with extract, transform, load and validate tasks. Retry logic and data integrity checks on every run. Production-grade pipeline deployed on Docker.',
      tech: ['Airflow', 'Docker', 'Python', 'PostgreSQL'],
      url: 'https://github.com/yustin-prz/etl-crypto-airflow',
      caseStudy: {
        problem: 'Manually fetching cryptocurrency market data for historical analysis is error-prone and doesn\'t scale — the goal was a repeatable, unattended daily process that captures a consistent market snapshot instead of ad-hoc pulls.',
        approach: 'Built a 4-stage Airflow DAG (extract → transform → load → validate) that pulls the top 100 coins from CoinGecko across 2 paginated requests, engineers 4 derived business metrics (market-cap tier, 24h performance, volume-to-cap ratio, snapshot date) and loads to PostgreSQL in append mode. Resilience is built in: a 2-retry policy with 5-minute delays plus explicit HTTP 429 rate-limit handling. Rather than fixing bad data after the fact, three validation gates run before a DAG run is marked successful — minimum row threshold, no nulls in the top-10 assets by market cap, and a Bitcoin-presence check.',
        results: 'Daily runs consistently load ~100 new records, transforming raw API responses into an 18-column analytical table, with all 3 validation gates passing on every run — the DAG has never marked a run successful over incomplete or invalid data.',
      },
    },
    {
      emoji: '📦',
      type: 'REST API · Backend',
      category: 'Backend',
      name: 'Order Management API',
      highlight: 'Full CRUD · layered API',
      desc: 'RESTful API for order management built with Node.js, Express and PostgreSQL. Full CRUD with layered architecture: routes, controllers, models and middleware validation.',
      tech: ['Node.js', 'Express', 'PostgreSQL', 'JavaScript'],
      url: 'https://github.com/yustin-prz/CRUD-JS-POSTAMAN-POSTGRESQL',
      caseStudy: {
        problem: 'An order and its line items have to stay consistent even when a write fails partway through — a naive multi-insert CRUD API can leave an order persisted with only half its items if one insert fails.',
        approach: 'Built a layered Express API (routes → controllers → model → PostgreSQL) where every create and update wraps the order and all of its items in a single SQL transaction (BEGIN / COMMIT / ROLLBACK), so a failure on any item insert rolls back the entire order instead of leaving partial data. A dedicated validation middleware checks types and business rules — required fields, positive quantities and prices, valid dates — before any query runs, returning structured 400 responses with a full list of errors instead of failing on the first one. Reads use a single query with json_agg/json_build_object to return each order pre-nested with its items, avoiding an N+1 query per order.',
        results: 'Full CRUD (create, list, find, update, delete) verified end-to-end via Postman against real PostgreSQL transactions, with the transactional insert model guaranteeing an order is never persisted without its items — even under a failed write.',
      },
    },
    {
      emoji: '🚗',
      type: 'Desktop App · C#',
      category: 'Backend',
      name: 'RoadReady — Vehicle Inspection',
      highlight: 'Layered + Factory pattern',
      desc: 'Vehicle inspection management system in C# (Windows Forms) with layered architecture, Factory Pattern, ADO.NET data access and RDLC report generation.',
      tech: ['C#', 'SQL Server', 'ADO.NET', 'Windows Forms'],
      url: 'https://github.com/yustin-prz/ProyectoRoadReady_YustinPerezCastro208390544',
      caseStudy: {
        problem: 'A vehicle-inspection office\'s appointment, invoicing and employee management needed a desktop system where business logic wouldn\'t be hardwired to one specific database connection or data-access implementation.',
        approach: 'Structured the app in classic layers — Windows Forms UI → BLL → DAL → Entities — with IBLL/IDAL interfaces so the business layer depends on abstractions instead of concrete data-access classes. Added a Factory Pattern (FactoryConexion / FactoryDatabase) that decides at runtime which DAL implementation and DB connection to instantiate, decoupling the rest of the app from a hardcoded ADO.NET setup. Integrated a live connected service to Costa Rica\'s Central Bank (BCCR) for currency exchange rates used in invoicing, and generated printable inspection and invoice documents with RDLC reports.',
        results: 'A working modular system covering appointments, invoicing, vehicles, employees and role-based security, with BCCR-driven currency conversion wired into invoicing and the DAL swappable through the Factory layer without touching BLL or UI code.',
      },
    },
    {
      emoji: '📊',
      type: 'SQL Analysis',
      category: 'BI & Analytics',
      name: 'Gold vs Economic Factors',
      highlight: '8 business questions · 4,137 rows',
      desc: '8 business questions answered on 4,137-row financial dataset using advanced SQL: CTEs, LAG(), CORR(), FILTER WHERE and UNION ALL on PostgreSQL.',
      tech: ['PostgreSQL', 'SQL', 'SQLAlchemy', 'Python'],
      url: 'https://github.com/yustin-prz/gold-sql-analysis',
      caseStudy: {
        problem: 'Gold is widely assumed to be a "safe haven" asset — rising when the dollar weakens or inflation spikes — but that\'s a narrative, not a verified fact. Needed to test it against 11 years of real data instead of assuming it.',
        approach: 'Loaded 4,137 rows of daily gold price (XAU/USD), US Dollar Index, crude oil and CPI inflation data (2015–2026) into PostgreSQL and answered 8 business questions using pure SQL — no pandas-side computation. Used CTEs with LAG() for year-over-year growth, CORR() to statistically quantify the relationship between gold and each economic factor, FILTER (WHERE ...) for conditional counts (years gold crossed $2K/$3K/$4K), and UNION ALL to combine top-10 and bottom-10 price-day rankings in one query.',
        results: 'Confirmed gold more than tripled (~$1,200 → $4,000+) between 2015 and 2026, quantified a negative correlation between gold and the Dollar Index in most years via CORR(), and showed gold priced measurably higher during high-inflation (>6%) periods — validating the safe-haven hypothesis with data instead of assuming it.',
      },
    },
    {
      emoji: '📈',
      type: 'Power BI · Analytics',
      category: 'BI & Analytics',
      name: 'US GDP vs Public Debt',
      highlight: '7 features · 3-page dashboard',
      desc: 'Cleaned 295-row time series (1947–2020), resolved unit inconsistency, engineered 7 features. 3-page Power BI executive dashboard with KPI cards and trend analysis.',
      tech: ['Python', 'Pandas', 'Power BI', 'DAX'],
      url: 'https://github.com/yustin-prz/us-gdp-debt-analysis',
      caseStudy: {
        problem: 'The raw FRED/Treasury dataset had 26.1% nulls in the public-debt column, GDP and debt expressed in different units despite both headers claiming "$mil", dates stored as strings, and a redundant index column — unusable for time-series analysis as-is.',
        approach: 'Ran a full data-quality diagnosis (nulls, dtypes, duplicates, temporal coverage) before touching anything, then built a reusable Python cleaning pipeline that standardized units, converted dates to proper datetime64, and made an explicit, documented decision not to impute the 77 historical nulls — quarterly debt wasn\'t systematically reported before 1966, so imputing would have fabricated data in a historically significant period. Engineered 7 derived columns (a recession flag from 2 consecutive negative-growth quarters, debt-to-GDP ratio, decade bucket, YoY growth), validated the output with a 10-check automated suite, then built a 3-page Power BI dashboard on top of the cleaned data.',
        results: 'Identified 2020 Q2 as the sharpest quarterly GDP drop in the entire series (-9.47%, nearly 3x the worst 2008 quarter) and showed the debt-to-GDP ratio climbing from ~40% in 1966 to 135.6% in 2020 — crossing 100% for the first time in 2013 and never returning to pre-crisis levels after any recession since 1980.',
      },
    },
    {
      emoji: '🧠',
      type: 'Power BI · Dashboard',
      category: 'BI & Analytics',
      name: 'Teen Mental Health',
      highlight: '1,200 records · wellbeing index',
      desc: 'Engineered composite wellbeing index and risk segmentation for 1,200 records. 4-page interactive Power BI dashboard with slicers and conditional formatting.',
      tech: ['Python', 'Power BI', 'DAX', 'Pandas'],
      url: 'https://github.com/yustin-prz/teen-mental-health-analysis',
      caseStudy: {
        problem: 'A raw 1,200-record survey of teen social-media habits and mental-health scores (stress, anxiety, addiction — each 1-10) doesn\'t tell a stakeholder anything actionable on its own. Needed to turn scattered scores into a clear view of who is at risk and what\'s driving it.',
        approach: 'Engineered 7 derived features on top of the original 13 — a composite 0-100 wellbeing index, a risk score and risk level from averaged stress + anxiety + addiction, and segments for sleep quality and social-media usage intensity — then built a 4-page interactive Power BI dashboard (overview, social media vs. mental health, sleep vs. academics, risk profile) with cross-filtering slicers by platform, gender and age group and conditional formatting to surface high-risk segments visually.',
        results: 'Segmented 23.7% of respondents into the high-risk bucket (wellbeing index 34.9/100, stress and anxiety near 8/10), found teens using both Instagram and TikTok reported the highest stress and anxiety of any platform group, and quantified that more screen time before sleep correlates with lower GPA — turning a flat survey dataset into an actionable risk-segmentation view.',
      },
    },
  ],
  // Order of the Projects filter tabs ("All" is prepended in the component)
  projectFilters: ['Data Engineering', 'ML', 'BI & Analytics', 'Backend', 'In Progress'],
  skills: [
    { category: 'Data Engineering', items: ['Apache Airflow', 'Apache Kafka', 'dbt', 'Docker', 'ETL/ELT', 'SQLAlchemy'] },
    { category: 'Languages & SQL', items: ['Python (Pandas)', 'SQL (Advanced)', 'JavaScript', 'TypeScript', 'C#'] },
    { category: 'Databases', items: ['PostgreSQL', 'MySQL', 'DuckDB', 'SQL Server'] },
    { category: 'ML & Analytics', items: ['XGBoost', 'Prophet', 'Random Forest', 'scikit-learn', 'Streamlit'] },
    { category: 'BI & Visualization', items: ['Power BI (DAX)', 'Data modeling', 'Power Query', 'Plotly', 'Matplotlib'] },
    { category: 'Backend & APIs', items: ['Node.js', 'Express', 'REST APIs', 'Postman'] },
    { category: 'Automation', items: ['Selenium', 'Excel VBA', 'Power Apps', 'Python scripting'] },
    { category: 'Cloud & DevOps', items: ['AWS', 'Google Cloud Platform (GCP)', 'Kubernetes', 'Jenkins', 'CI/CD', 'Git', 'GitHub'] },
  ],
  // 7 verified certs, all with credential links
  certifications: [
    { name: 'Data Analytics Essentials', issuer: 'Cisco Networking Academy', date: 'May 2026', icon: '📊', link: 'https://www.credly.com/badges/239d5ec2-98dd-4492-9acb-3cf0f5104f56' },
    { name: 'Python Essentials 2', issuer: 'Cisco Networking Academy / Python Institute', date: 'Feb 2026', icon: '🐍', link: 'https://www.credly.com/badges/60151291-fd02-401c-8d61-2a6e97c99e9f' },
    { name: 'Fundamentos de Machine Learning', issuer: 'Fundación Carlos Slim — Capacítate para el Empleo', date: 'May 2026', icon: '🤖', link: 'https://capacitateparaelempleo.org/verifica/07cb7a3e-81a9-4ccf-a02f-4fbd1a9e4171/54584cf3-2ba9-46c3-8451-2db69afe7fde' },
    { name: 'Power BI Dual Certification', issuer: 'Udemy', date: 'January 2025', icon: '📈', link: 'https://ude.my/UC-d7521e99-219d-45fe-ae30-b7cf896089eb' },
    { name: 'Introduction to Data Science', issuer: 'Cisco Networking Academy', date: 'May 2026', icon: '🔬', link: 'https://www.credly.com/badges/0c81c19e-86bb-49e0-9d39-691e04f1ee8f' },
    { name: 'EF SET Certificate — C1 Advanced', issuer: 'EF Education First', date: 'June 2026', icon: '🗣️', link: 'https://cert.efset.org/YSh6id' },
    { name: 'Google Cloud Computing Foundations Certificate', issuer: 'Google Cloud', date: 'August 2026', icon: '☁️', link: 'https://www.credly.com/badges/aca8373d-6328-49b2-b8a2-570b4390ab17' },
  ],
  // Data behind the "Recruiter view" floating summary panel
  recruiterSummary: {
    role: 'Data Engineer (in training) · Data Analyst',
    availability: 'Open to internships & junior data roles — Costa Rica or remote',
    topAchievement: 'Cut a production AR pipeline\'s execution time by 75% at DHL — a solution now scaling across 8 South American countries.',
    topSkills: ['Python', 'SQL', 'dbt', 'Airflow', 'Kafka', 'Power BI'],
    metrics: [
      { value: '-75%', label: 'Pipeline runtime' },
      { value: '8', label: 'Countries scaling' },
      { value: '100k+', label: 'Records / dataset' },
      { value: '11/11', label: 'dbt tests passing' },
    ],
  },
};
